on: workflow_dispatch
name: 90 - Génération des secrets
jobs:
  gen-secrets:
    name: 90 - Génération des secrets
    runs-on: ubuntu-latest
    steps:
    - name: Récupération du repository
      uses: actions/checkout@master
    - name: Exécution du script
      run: bash comptes/gen_secrets.sh
    - name: Enregistrement des artefacts (annuaire LDAP)
      uses: actions/upload-artifact@v4
      with:
        name: annuaire-ldap.ldif
        path: comptes/sortie/annuaire-ldap.ldif
    - name: Enregistrement des artefacts (Comptes PgSQL)
      uses: actions/upload-artifact@v4
      with:
        name: secrets-pgsql.yaml
        path: comptes/sortie/secrets.yaml
    - name: Enregistrement des artefacts (Fichier CSV)
      uses: actions/upload-artifact@v4
      with:
        name: recapitulatif.csv
        path: comptes/sortie/recapitulatif.csv